name: Publich on Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test 123
        run: |
          git config --global user.name 'Deploy Jocke'
          git config --global user.email 'samlarsson94@gmail.com'

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.78.2/hugo_0.78.2_Linux-64bit.deb
          sudo dpkg -i hugo_0.78.2_Linux-64bit.deb

    #https://github.com/gohugoio/hugo/releases/download/v0.78.2/hugo_0.78.2_Linux-64bit.deb
      # - name: Install Hugo
      #   run: |
      #     wget https://github.com/gohugoio/hugo/releases/download/v0.63.2/hugo_0.63.2_Linux-64bit.deb
      #     sudo dpkg -i hugo_0.63.2_Linux-64bit.deb

    #   - name: Build site with Hugo
    #     run: |
    #       /usr/local/bin/hugo -E -F --baseURL=/ --minify --source hugo

      - name: Test
        run: |
          git checkout --orphan gh-pages
          npm install
          npm run css:build
          npm run js:build
          /usr/local/bin/hugo -E -F --baseURL=/slarsson/ --minify
          bash .github/nojekyll.sh
          git --work-tree public add --all
          git --work-tree public commit -m 'DEPLOY'
          git push origin HEAD:gh-pages --force
