name: Publish on Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
          git config --global user.name 'Deploy Jocke'
          git config --global user.email 'samlarsson94@gmail.com'

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.78.2/hugo_0.78.2_Linux-64bit.deb
          sudo dpkg -i hugo_0.78.2_Linux-64bit.deb

      - name: Run npm install
        run: npm install

      - name: Build
        run: |
          npm run css:build
          npm run js:build
          /usr/local/bin/hugo -E -F --baseURL=/slarsson/ --minify 
          bash .github/nojekyll.sh

      - name: Add build to gh-pages
        run: |
          git checkout --orphan gh-pages
          git --work-tree public add --all
          git --work-tree public commit -m 'SHA: $GITHUB_SHA'
          git push origin HEAD:gh-pages --force