name: Publich on Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.63.2/hugo_0.63.2_Linux-64bit.deb
          sudo dpkg -i hugo_0.63.2_Linux-64bit.deb

    #   - name: Build site with Hugo
    #     run: |
    #       /usr/local/bin/hugo -E -F --baseURL=/ --minify --source hugo

      - name: Test
        run: |
          git checkout --orphan gh-pages
          /usr/local/bin/hugo -E -F --baseURL=/ --minify
          git --work-tree public add --all
          git --work-tree public commit -m 'DEPLOY'
          git push origin HEAD:gh-pages --force
